name: Test

on:
  push:            # Trigger the workflow on every commit/push
    branches:
      - '**'       # '**' means all branches
  workflow_dispatch:   # Optional manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python3 log_parser.py
