name: Test

on:
  push:            # Trigger the workflow on every commit/push
    branches:
      - '**'       # '**' means all branches
  workflow_dispatch:   # Optional manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python3 log_parser.py

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Check docker version
        run: docker --version
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          token: ${{ secrets.DOCKER_TOKEN }}  
      - name: Build Docker image
        run: docker build -t log_parser:latest .
      - name: Push Docker image
        run: docker push log_parser:latest && echo "Job done!!"
    
